### ISSUE TITLE
macos m1: illegal byte sequence errors from sed

### ISSUE THREAD

**Issue by sdondley** [sturob/tmux-teleport#2]
I was getting these errors. I installed gsed with homebrew and modified the preview.sh script to call gsed instead of sed. I see 

`LC_CTYPE=C # workaround for "sed: RE error: illegal byte sequence" error on macOS`

at the top of the file. Not sure why it's not working for me.

**Comment by sturob** [comment]
Thanks for this. Should be fixed now even without gsed installed.
